### PR TITLE
just started to work

### PR DESCRIPTION
**Pull request by WardCunningham**
Can't get server-side to load.

Notes in wiki:
http://ward.asia.wiki.org/friendly-security.html

I'm off to lunch. Then more debugging.

### CODE REVIEW

**Comment by WardCunningham** [comment]
I try launching with `node index.js`, more messages.

image

**Comment by paul90** [comment]
Not sure were that require error is coming from - did you run `npm install`?

Also, are you starting from `wiki@next`? Forgot to mention that is the starting point, there a placeholders in the client page that were not available before then.

**Comment by WardCunningham** [comment]
I used npm to do a local install.
```
npm i wiki@next
```
I then went to the installed wiki and added friends, first with link, later with file reference.
```
cd ~/node_modules/wiki
npm i ../../FedWiki/wiki-security-friends
```
I am recalling this from memory. I tested that wiki was finding something by substituting `friendsx` for `friends` and getting a different error message. 

I didn't find any build logic for the server side. My editor config runs coffee for me on save leaving a .js in the same directory. I gather that node is running coffee translation for me on load. 

I wonder if there is some weakness in my approach. Another would be to build wiki and wiki-server from github branch and assemble them together. I thought the npm install of wiki@next would be a safe shortcut.

**Comment by paul90** [comment]
Very strange. Can you delete the `.js` file your editor is creating and try again.

**Comment by WardCunningham** [comment]
Yes, tried that, no change.

**Pull request merged**
